// Action Types for album-related actions
export const CREATE_ALBUM_SUCCESS = 'CREATE_ALBUM_SUCCESS';
export const CREATE_ALBUM_FAILURE = 'CREATE_ALBUM_FAILURE';
export const READ_ALBUMS_SUCCESS = 'READ_ALBUMS_SUCCESS';
export const READ_ALBUMS_FAILURE = 'READ_ALBUMS_FAILURE';
export const READ_ALBUM_SUCCESS = 'READ_ALBUM_SUCCESS';
export const READ_ALBUM_FAILURE = 'READ_ALBUM_FAILURE';
export const UPDATE_ALBUM_SUCCESS = 'UPDATE_ALBUM_SUCCESS';
export const UPDATE_ALBUM_FAILURE = 'UPDATE_ALBUM_FAILURE';
export const DELETE_ALBUM_SUCCESS = 'DELETE_ALBUM_SUCCESS';
export const DELETE_ALBUM_FAILURE = 'DELETE_ALBUM_FAILURE';
export const SEARCH_ALBUMS_SUCCESS = 'SEARCH_ALBUMS_SUCCESS';
export const SEARCH_ALBUMS_FAILURE = 'SEARCH_ALBUMS_FAILURE';
